kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: ghost
provisioner: efs.csi.aws.com
parameters:
  provisioningMode: efs-ap
  fileSystemId: fs-0c16ff26b7597d151
  directoryPerms: "700"